config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'

  authenticated :user do
    resources :categories do
      resources :expenses
    end
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expense_categories
  has_many :expenses, through: :expense_categories

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :expense_categories
  has_many :expenses, through: :expense_categories

  validates :name, presence: true, length: { minimum: 2 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  default_scope { order(created_at: :desc) }
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  belongs_to :expense
  belongs_to :category
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  has_many :transaction_categories
  has_many :transactions, through: :transaction_categories

  validates :name, presence: true
  validates :amount, presence: true

  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :transactions

  validates :name, presence: true, length: { in: 2..40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  helper_method :current_user
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show destroy]

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      handle_uploaded_icon_file if category_params[:icon].present?
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @expenses = @category.expenses.order(created_at: :desc)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def handle_uploaded_icon_file
    uploaded_file = category_params[:icon]
    file_path = Rails.root.join('public', 'uploads', uploaded_file.original_filename)

    File.binwrite(file_path, uploaded_file.read)

    @category.update(icon: File.join('/uploads', uploaded_file.original_filename))
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  def index
    @expenses = current_user.expenses.order(created_at: :desc)
  end

  def show
    @expense = Expense.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
    @expense = Expense.new
    @selected_category_ids = []
  end

  def create
    primary_category_id = params[:expense][:primary_category_id]
    additional_category_ids = params[:additional_category_ids] || []

    name = params[:expense][:name]
    amount = params[:expense][:amount]

    @expense = Expense.new(name:, amount:, user: current_user)

    if @expense.save
      ExpenseCategory.create(expense_id: @expense.id, category_id: primary_category_id)

      additional_category_ids.each do |category_id|
        next if category_id.blank?

        ExpenseCategory.create(expense_id: @expense.id, category_id:)
      end

      redirect_to category_path(primary_category_id), notice: 'Expense was successfully created.'
    else
      @categories = current_user.categories
      render :new
    end
  end

  def edit; end

  def update
    if @expense.update(expense_params)
      @expense.category_ids = params[:expense][:category_ids]
      redirect_to @expense, notice: 'Expense was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to expenses_url, notice: 'Expense was successfully destroyed.'
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :user_id, category_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="full-page">
  <div class="navigation">
    <ul>
      <li><%= link_to image_tag('backarrow.png', alt: 'Back'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %></li>
      <h2>Categories</h2>
      <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
    </ul>
  </div>
  <div class="categories-list">
    <% @categories.each do |category| %>
      <%= link_to category do %>
        <div class="category-item">
          <div class="category-left">
            <% if category.icon.present? %>
              <img src="<%=category.icon %>" alt="<%=category.name %>" class='category-icon' />
            <% end %>
          </div>
          <div class="category-center">
            <h3><%= category.name %></h3>
            <p><%= category.created_at %></p>
          </div>
          <p>$ <%= category.expenses.sum(:amount) %></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="new-category">
    <div class="new-category-inner">
      <%= link_to "Add a New Category", new_category_path, class: "new-category-button" %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="navigation">
  <ul>
    <li><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2>Create A Category</h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-class">
  <%= form_with(model: @category, url: categories_path, method: :post, multipart: true) do |form| %>
    <%= form.text_field :name, placeholder: "Enter the name" %>
    <%= form.file_field :icon, id: 'icon_upload' %>
    <%= form.submit "Create Category" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="full-page">
  <div class="navigation">
    <ul>
      <li><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
      <h2><%= @category.name %></h2>
      <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
    </ul>
  </div>
  <div class="category-header">
    <p><%= @category.name %></p>
    <p>$ <%= @category.expenses.sum(:amount) %></p>
  </div>
  <div class="expenses-container">
    <% @category.expenses.each do |expense| %>
      <div class="expense-item">
        <%= link_to expense.name, category_expense_path(@category, expense) %>
        $ <%= expense.amount %>
      </div>
    <% end %>
  </div>
  <div class="new-category">
    <div class="new-category-inner">
      <%= link_to "Add a New expense", new_category_expense_path(@category) %>
    </div>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="navigation">
  <ul>
    <li><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(params[:category_id]), class: 'nav-link' %></li>
    <li>
      <h2>Add a new Expense</h2>
    </li>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %></li>
  </ul>
</div>
<div class="form-class">
  <%= form_with(model: [@category, @expense], url: category_expenses_path(@category), method: :post, id: 'expense-form') do |form| %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter Expense Name' %>
    <%= form.text_field :amount, class: 'form-control', placeholder: 'Enter Expense Amount' %>
    <%= form.hidden_field :primary_category_id, value: @category.id %>
    <% @categories.each do |category| %>
      <% next if category == @category %>
      <%= check_box_tag 'additional_category_ids[]', category.id, false, id: "additional_category_ids_#{category.id}", class: 'form-checkbox' %>
      <%= label_tag "additional_category_ids_#{category.id}", category.name, class: 'checkbox-label' %>
    <% end %>
    <%= form.submit 'Create Expense', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/expenses/show.html.erb
<div class="navigation">
  <ul>
    <li><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(params[:category_id]), class: 'nav-link' %></li>
    <h2>Expense: <%= @expense.name %></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<div class="expense-container">
  <div class="expense-heading">
    <p><%= @expense.name %></p>
    <p><strong>Amount:</strong> <%= @expense.amount %></p>
  </div>
  <div class="expense-details">
    <h2>Categories:</h2>
    <ul>
      <% @expense.categories.each do |category| %>
        <li><%= category.name %></li>
      <% end %>
    </ul>
    <p><strong>Created At:</strong> <%= @expense.created_at.strftime('%B %d, %Y %I:%M %p') %></p>
  </div>
</div>

app/views/home/index.html.erb
<div class = "home-container">
  <div class="top">
    <h1>Budget App</h1>
  </div>
  <div class= "bottom">
    <% if user_signed_in? %>
      <%= link_to 'Enter App', categories_path, class: "nav-link-login" %>
    <% else %>
      <%= link_to 'Log In', new_user_session_path, class: "nav-link-login" %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link-signup" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="nav-list">
      <% if current_page?(categories_path) %>
        <li class="nav-item">
          <%= link_to image_tag('backarrow.png', alt: 'Back'), class: 'nav-link' %>
        </li>
        <h2>Categories</h2>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </header>

app/views/transactions/new.html.erb
<div class="navigation">
  <ul>
    <li><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(params[:category_id]), class: 'nav-link' %></li>
    <li>
      <h2>Add a new Transaction</h2>
    </li>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %></li>
  </ul>
</div>
<div class="form-class">
  <%= form_with(model: [@category, @transaction], url: category_transactions_path(@category), method: :post, id: 'transaction-form') do |form| %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter Name for Transaction' %>
    <%= form.text_field :amount, class: 'form-control', placeholder: 'Enter Amount for Transaction' %>
    <%= form.hidden_field :primary_category_id, value: @category.id %>
    <% @categories.each do |category| %>
      <% next if category == @category %>
      <%= check_box_tag 'additional_category_ids[]', category.id, false, id: "additional_category_ids_#{category.id}", class: 'form-checkbox' %>
      <%= label_tag "additional_category_ids_#{category.id}", category.name, class: 'checkbox-label' %>
    <% end %>
    <%= form.submit 'Create Transaction', class: 'btn btn-primary' %>
  <% end %>
</div>